### ISSUE TITLE
Dúvida: Ruído (Espacialmente) Correlacionado

### ISSUE THREAD

**Issue by santosbruno85** [psrenergy/PAR.jl#5]
Na construção do Ruído (Espacialmente) Correlacionado (linha 181, PARp.jl), a matriz L não deveria ser transposta para ser multiplicada pela esquerda?

**Comment by guilhermebodin** [comment]
Deveria, uma explicação mais detalhada seria essa. Assumindo um caso em que temos 10 modelos e 500 cenários estamos montando uma matriz `ruido_normal(500, 10)`. Originalmente a matriz L deveria ser multiplicada pela esquerda:
```math
L \cdot v \quad v \sim \mathcal{N}(0, 1)
```
Isso seria equivalente a fazer
```julia
ruido_correlacionado = zeros(500, 10)
for i in 1:n_scenarios
    ruido_correlacionado[i, :] = L * ruido_normal[i, :]
end
```
Mas poderíamos ser mais espertos e fazer
```
ruido_correlacionado = (L * ruido_normal')'
```
Simplificando ainda mais deveriamos ter
```
ruido_correlacionado = ruido_normal * L'
```
que pode ser escrito como a multiplicação pela direita da parte triangular superior da decomposição de chosleky da matriz de correlação.
```
ruido_correlacionado = ruido_normal * cholesky(cor_matrix).U
```


referência: https://math.stackexchange.com/questions/2079137/generating-multivariate-normal-samples-why-cholesky
